#pragma once

#include "di/reflect/enumerator.h"
#include "di/reflect/reflect.h"

// Key reference: https://sw.kovidgoyal.net/kitty/keyboard-protocol/
namespace ttx {
enum class Key {
    None,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    _0,
    _1,
    _2,
    _3,
    _4,
    _5,
    _6,
    _7,
    _8,
    _9,

    Backtick,
    Minus,
    Equal,
    Star,
    Plus,
    LeftBracket,
    RightBracket,
    BackSlash,
    SemiColon,
    Quote,
    Comma,
    Period,
    Slash,

    Escape,
    Enter,
    Tab,
    Backspace,
    Space,
    Insert,
    Delete,
    Left,
    Right,
    Up,
    Down,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,
    Menu,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,

    KeyPad0,
    KeyPad1,
    KeyPad2,
    KeyPad3,
    KeyPad4,
    KeyPad5,
    KeyPad6,
    KeyPad7,
    KeyPad8,
    KeyPad9,
    KeyPadDecimal,
    KeyPadDivide,
    KeyPadMultiply,
    KeyPadSubtract,
    KeyPadAdd,
    KeyPadEnter,
    KeyPadEqual,
    KeyPadSeparator,
    KeyPadLeft,
    KeyPadRight,
    KeyPadUp,
    KeyPadDown,
    KeyPadPageUp,
    KeyPadPageDown,
    KeyPadHome,
    KeyPadEnd,
    KeyPadInsert,
    KeyPadDelete,
    KeyPadBegin,

    MediaPlay,
    MediaPause,
    MediaPlayPause,
    MediaReverse,
    MediaStop,
    MediaFastForward,
    MediaRewind,
    MediaTrackNext,
    MediaTrackPrevious,
    MediaRecord,
    LowerVolume,
    RaiseVolume,
    MuteVolume,

    ModifiersBegin,
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    LeftHyper,
    LeftMeta,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    RightHyper,
    RightMeta,
    IsoLevel3Shift,
    IsoLevel5Shift,
    ModifiersEnd,

    KeyMax,
};

constexpr auto tag_invoke(di::Tag<di::reflect>, di::InPlaceType<Key>) {
    using enum Key;
    return di::make_enumerators<"Key", "Represents a supported key for specifying key bindings">(
        di::enumerator<"none", None, "Disables a key binding">, di::enumerator<"a", A>, di::enumerator<"b", B>,
        di::enumerator<"c", C>, di::enumerator<"d", D>, di::enumerator<"e", E>, di::enumerator<"f", F>,
        di::enumerator<"g", G>, di::enumerator<"h", H>, di::enumerator<"i", I>, di::enumerator<"j", J>,
        di::enumerator<"k", K>, di::enumerator<"l", L>, di::enumerator<"m", M>, di::enumerator<"n", N>,
        di::enumerator<"o", O>, di::enumerator<"p", P>, di::enumerator<"q", Q>, di::enumerator<"r", R>,
        di::enumerator<"s", S>, di::enumerator<"t", T>, di::enumerator<"u", U>, di::enumerator<"v", V>,
        di::enumerator<"w", W>, di::enumerator<"x", X>, di::enumerator<"y", Y>, di::enumerator<"z", Z>,
        di::enumerator<"0", _0>, di::enumerator<"1", _1>, di::enumerator<"2", _2>, di::enumerator<"3", _3>,
        di::enumerator<"4", _4>, di::enumerator<"5", _5>, di::enumerator<"6", _6>, di::enumerator<"7", _7>,
        di::enumerator<"8", _8>, di::enumerator<"9", _9>, di::enumerator<"`", Backtick>, di::enumerator<"-", Minus>,
        di::enumerator<"=", Equal>, di::enumerator<"*", Star>, di::enumerator<"+", Plus>,
        di::enumerator<"[", LeftBracket>, di::enumerator<"]", RightBracket>, di::enumerator<"\\", BackSlash>,
        di::enumerator<";", SemiColon>, di::enumerator<"'", Quote>, di::enumerator<",", Comma>,
        di::enumerator<".", Period>, di::enumerator<"/", Slash>, di::enumerator<"esc", Escape>,
        di::enumerator<"enter", Enter>, di::enumerator<"tab", Tab>, di::enumerator<"backspace", Backspace>,
        di::enumerator<"space", Space>, di::enumerator<"insert", Insert>, di::enumerator<"delete", Delete>,
        di::enumerator<"left", Left>, di::enumerator<"right", Right>, di::enumerator<"up", Up>,
        di::enumerator<"down", Down>);
}
}
