# This file was autogenerated via `ttx config nix`. Do not modify.
{ lib, ... }:
with lib.types;
let
  clipboard = submodule {
    options = {
      "mode" = lib.mkOption {
        type = nullOr (clipboardMode);
        description = "Configure the way ttx interacts with the system clipboard when inner applications use OSC 52. By default ttx will read/write from the system clipboard. This requires configuring your terminal emulator to allow interacting with the system clipboard. If you do not want applications to access your system clipboard, specify the mode as 'local'";
        default = null;
      };
    };
  };
  clipboardMode = enum [
    "system"
    "system-write-local-read"
    "system-write-no-read"
    "local"
    "local-write-no-read"
    "disabled"
  ];
  colors = submodule {
    options = {
      "palette" = lib.mkOption {
        type = nullOr (listOf (str));
        description = "The terminal palette colors to use as an array. Up to 256 colors can be specified but typically only the first 16 are, which correspond the typical ANSI colors";
        default = null;
      };
      "foreground" = lib.mkOption {
        type = nullOr (str);
        description = "The default foreground color to use in the terminal";
        default = null;
      };
      "background" = lib.mkOption {
        type = nullOr (str);
        description = "The default background color to use in the terminal";
        default = null;
      };
      "selection_background" = lib.mkOption {
        type = nullOr (str);
        description = "The background color to use when highlighting selection text. A value of dynamic will cause the foreground and background to be swapped for selected cells";
        default = null;
      };
      "selection_foreground" = lib.mkOption {
        type = nullOr (str);
        description = "The foreground color to use when highlighting selection text. A value of dynamic will cause the foreground and foreground to be swapped for selected cells";
        default = null;
      };
      "cursor" = lib.mkOption {
        type = nullOr (str);
        description = "The default color to use when displaying the cursor. A value of dynamic indicates the default foreground color will be used";
        default = null;
      };
      "cursor_text" = lib.mkOption {
        type = nullOr (str);
        description = "The default color to use when displaying text under the cursor. A value of dynamic indicates the default background color will be used";
        default = null;
      };
    };
  };
  config = submodule {
    options = {
      "$schema" = lib.mkOption {
        type = str;
        default = null;
      };
      "version" = lib.mkOption {
        type = ints.u32;
        description = "Version of the ttx config (should always be 1)";
        default = null;
      };
      "extends" = lib.mkOption {
        type = nullOr (listOf (str));
        description = "List of configuration files to extend. These can recursively extend more files. Priority is given to the last time the configuration option is specified";
        default = null;
      };
      "theme" = lib.mkOption {
        type = nullOr theme;
        description = "Configure the theme used by ttx";
        default = null;
      };
      "input" = lib.mkOption {
        type = nullOr input;
        description = "Configuration relating the input processing of ttx (primarily key bindings)";
        default = null;
      };
      "colors" = lib.mkOption {
        type = nullOr colors;
        description = "Terminal colors to use (main color palette)";
        default = null;
      };
      "clipboard" = lib.mkOption {
        type = nullOr clipboard;
        description = "Configuration relating to the clipboard handling of ttx (OSC 52)";
        default = null;
      };
      "session" = lib.mkOption {
        type = nullOr session;
        description = "Configuration relating the session management, such as automatically saving and restoring the current layout";
        default = null;
      };
      "shell" = lib.mkOption {
        type = nullOr shell;
        description = "Configuration relating to the shell ttx starts in each pane";
        default = null;
      };
      "fzf" = lib.mkOption {
        type = nullOr fzf;
        description = "Configuration for ttx built-in fzf popups";
        default = null;
      };
      "status_bar" = lib.mkOption {
        type = nullOr statusBar;
        description = "Configuration for the status bar";
        default = null;
      };
      "terminfo" = lib.mkOption {
        type = nullOr terminfo;
        description = "Configuration relating to the terminfo ttx passes to inner applications";
        default = null;
      };
    };
  };
  fzf = submodule {
    options = {
      "colors" = lib.mkOption {
        type = nullOr fzfColors;
        description = "Configure the theme used by fzf popups";
        default = null;
      };
    };
  };
  fzfColors = submodule {
    options = {
      "fg" = lib.mkOption {
        type = nullOr (str);
        description = "Text color of unselected entries";
        default = null;
      };
      "fg+" = lib.mkOption {
        type = nullOr (str);
        description = "Text color of selected entries";
        default = null;
      };
      "bg" = lib.mkOption {
        type = nullOr (str);
        description = "Background color of unselected entries";
        default = null;
      };
      "bg+" = lib.mkOption {
        type = nullOr (str);
        description = "Background color of selected entries";
        default = null;
      };
      "border" = lib.mkOption {
        type = nullOr (str);
        description = "Outer border color";
        default = null;
      };
      "header" = lib.mkOption {
        type = nullOr (str);
        description = "Text color of the fzf header";
        default = null;
      };
      "hl" = lib.mkOption {
        type = nullOr (str);
        description = "Text color to show the matched parts of an entry";
        default = null;
      };
      "hl+" = lib.mkOption {
        type = nullOr (str);
        description = "Text color to show the matched parts of selected entries";
        default = null;
      };
      "info" = lib.mkOption {
        type = nullOr (str);
        description = "Text color for info (located on the right of the prompt line)";
        default = null;
      };
      "label" = lib.mkOption {
        type = nullOr (str);
        description = "Text color for text placed in an fzf border";
        default = null;
      };
      "marker" = lib.mkOption {
        type = nullOr (str);
        description = "Text color of multi-select indicator";
        default = null;
      };
      "pointer" = lib.mkOption {
        type = nullOr (str);
        description = "Text color of current entry indicator";
        default = null;
      };
      "preview-border" = lib.mkOption {
        type = nullOr (str);
        description = "Border color for the preview window";
        default = null;
      };
      "prompt" = lib.mkOption {
        type = nullOr (str);
        description = "Text color of the query prompt";
        default = null;
      };
      "selected-bg" = lib.mkOption {
        type = nullOr (str);
        description = "Background color of selected entries";
        default = null;
      };
      "separator" = lib.mkOption {
        type = nullOr (str);
        description = "Color of line separator below the query text";
        default = null;
      };
      "spinner" = lib.mkOption {
        type = nullOr (str);
        description = "Color of the loading spinner";
        default = null;
      };
    };
  };
  input = submodule {
    options = {
      "prefix" = lib.mkOption {
        type = nullOr (key);
        description = "Prefix key to use. Almost all key bindings require using the prefix key to enter 'NORMAL' mode first. Currently, the prefix key must be pressed in conjunction with the control key. So specifying a prefix of 'A' means that to enter 'NORMAL' mode you must press 'ctrl+a'";
        default = null;
      };
      "disable_default_keybinds" = lib.mkOption {
        type = nullOr (bool);
        description = "Disable all default key bindings to allow full customization";
        default = null;
      };
      "save_state_path" = lib.mkOption {
        type = nullOr (str);
        description = "Path to write save state files captured by ttx. These save state files can be replayed using `ttx replay`. This functionality is useful for testing and reproducing bugs";
        default = null;
      };
    };
  };
  key = enum [
    "None"
    "A"
    "B"
    "C"
    "D"
    "E"
    "F"
    "G"
    "H"
    "I"
    "J"
    "K"
    "L"
    "M"
    "N"
    "O"
    "P"
    "Q"
    "R"
    "S"
    "T"
    "U"
    "V"
    "W"
    "X"
    "Y"
    "Z"
    "0"
    "1"
    "2"
    "3"
    "4"
    "5"
    "6"
    "7"
    "8"
    "9"
    "Backtick"
    "Minus"
    "Equal"
    "Star"
    "Plus"
    "LeftBracket"
    "RightBracket"
    "BackSlash"
    "SemiColon"
    "Quote"
    "Comma"
    "Period"
    "Slash"
    "Escape"
    "Enter"
    "Tab"
    "Backspace"
    "Space"
    "Insert"
    "Delete"
    "Left"
    "Right"
    "Up"
    "Down"
  ];
  session = submodule {
    options = {
      "restore_layout" = lib.mkOption {
        type = nullOr (bool);
        description = "Automatically restore the previous layout on startup. This does not preserve commands but does restore all sessions, tabs, and panes as well as their working directories";
        default = null;
      };
      "save_layout" = lib.mkOption {
        type = nullOr (bool);
        description = "Automaticaly save the current layout to a file whenever updates occur. The layout is saved to $XDG_DATA_HOME/ttx/layouts (~/.local/share/ttx/layouts). The layout file is meant for use the `restore_layout` option";
        default = null;
      };
      "layout_name" = lib.mkOption {
        type = nullOr (str);
        description = "Layout name to use for save/restore. This defaults the name of the chosen profile";
        default = null;
      };
    };
  };
  shell = submodule {
    options = {
      "command" = lib.mkOption {
        type = nullOr (listOf (str));
        description = "The command to run inside is pane. This is a list of arguments passed directly to the OS. If shell expansion is desired, use a command like this: [\"sh\", \"-c\", \"<COMMAND>\"]. By default '$SHELL' is started with no additional arguments";
        default = null;
      };
    };
  };
  statusBar = submodule {
    options = {
      "hide" = lib.mkOption {
        type = nullOr (bool);
        description = "Hide the status bar. This is useful for minimal layouts or for testing";
        default = null;
      };
      "colors" = lib.mkOption {
        type = nullOr statusBarColors;
        description = "Configure the colors used by the status bar";
        default = null;
      };
    };
  };
  statusBarColors = submodule {
    options = {
      "badge_text_color" = lib.mkOption {
        type = nullOr (str);
        description = "The text color to use for colored badges (the left part of status bar components). A value of dynamic means use the default background color as the text color";
        default = null;
      };
      "label_text_color" = lib.mkOption {
        type = nullOr (str);
        description = "The text color to use for the text label of tabs";
        default = null;
      };
      "background_color" = lib.mkOption {
        type = nullOr (str);
        description = "The default background color to use for the status bar";
        default = null;
      };
      "label_background_color" = lib.mkOption {
        type = nullOr (str);
        description = "The background color to use for tab labels";
        default = null;
      };
      "active_tab_badge_color" = lib.mkOption {
        type = nullOr (str);
        description = "The color to use to signify a tab is active";
        default = null;
      };
      "inactive_tab_badge_color" = lib.mkOption {
        type = nullOr (str);
        description = "The color to use to signify a tab is inactive";
        default = null;
      };
      "session_badge_background_color" = lib.mkOption {
        type = nullOr (str);
        description = "The background color to use for the session name badge";
        default = null;
      };
      "host_badge_background_color" = lib.mkOption {
        type = nullOr (str);
        description = "The background color to use for the host name badge";
        default = null;
      };
      "switch_mode_color" = lib.mkOption {
        type = nullOr (str);
        description = "The color to use to signify you are in SWITCH mode";
        default = null;
      };
      "insert_mode_color" = lib.mkOption {
        type = nullOr (str);
        description = "The color to use to signify you are in INSERT mode";
        default = null;
      };
      "normal_mode_color" = lib.mkOption {
        type = nullOr (str);
        description = "The color to use to signify you are in NORMAL mode";
        default = null;
      };
      "resize_mode_color" = lib.mkOption {
        type = nullOr (str);
        description = "The color to use to signify you are in RESIZE mode";
        default = null;
      };
    };
  };
  terminfo = submodule {
    options = {
      "term" = lib.mkOption {
        type = nullOr (str);
        description = "Value of the TERM enviornment variable to pass to inner applications. ttx automaticaly sets up the terminfo so the default value of 'xterm-ttx' will work locally. However, ttx's terminfo is not automaticaly available when using ssh or sudo. If this is causing issues, set this option to 'xterm-256color'";
        default = null;
      };
      "force_local_terminfo" = lib.mkOption {
        type = nullOr (bool);
        description = "Compile ttx's terminfo on startup and set TERMINFO_DIR, even if the terminfo is already installed. This shouldn't be necessary but can be used if the system's terminfo is broken or for testing";
        default = null;
      };
    };
  };
  theme = submodule {
    options = {
      "name" = lib.mkOption {
        type = nullOr (str);
        description = "The named theme to use. When not set, ttx will try to auto-detect your terminal's color scheme against the list built-in theme, unless theme auto detection is disabled via config or `--detect-theme=disabled`. When auto detection fails, the standard 16 ANS colors will be used, with the theme name set to 'ansi'. When providing a named theme, ttx first searches the directory `$XDG_CONFIG_HOME/ttx/themes` for a JSON configuration file matching the name. The file's name should be the theme's name followed by `.json`. Custom themes use the same JSON schema as normal configuration files, and can include any property. However, built-in themes only configure colors. When no custom theme is found, ttx searches its set of built-in schemes. The built-in themes are taken from the [tinted terminal repository](https://github.com/tinted-theming/tinted-terminal). Configuration defined in a theme has lower precedence than any setting defined in a configuration file. If you want settings to be modifable by the theme you select you cannot specify the option your main configuration file";
        default = null;
      };
    };
  };
in
lib.mkOption {
  type = attrsOf config;
  default = { };
  description = ''
    Attribute set representing a set ttx configuration files to be written to `$XDG_CONFIG_HOME/ttx`.
    Each file name is accessible as a ttx profile.
    The default ttx profile is `main`, and is commonly the only configuration file which must be defined.'';
  example = {
    main = {
      input = {
        prefix = "A";
      };
    };
  };
}
