var annotated_dup =
[
    [ "ttx", "namespacettx.html", [
      [ "json", "namespacettx_1_1json.html", [
        [ "v1", "namespacettx_1_1json_1_1v1.html", [
          [ "Pane", "structttx_1_1json_1_1v1_1_1Pane.html", "structttx_1_1json_1_1v1_1_1Pane" ],
          [ "PaneLayoutVariant", "structttx_1_1json_1_1v1_1_1PaneLayoutVariant.html", "structttx_1_1json_1_1v1_1_1PaneLayoutVariant" ],
          [ "PaneLayoutNode", "structttx_1_1json_1_1v1_1_1PaneLayoutNode.html", "structttx_1_1json_1_1v1_1_1PaneLayoutNode" ],
          [ "Tab", "structttx_1_1json_1_1v1_1_1Tab.html", "structttx_1_1json_1_1v1_1_1Tab" ],
          [ "Session", "structttx_1_1json_1_1v1_1_1Session.html", "structttx_1_1json_1_1v1_1_1Session" ],
          [ "LayoutState", "structttx_1_1json_1_1v1_1_1LayoutState.html", "structttx_1_1json_1_1v1_1_1LayoutState" ]
        ] ]
      ] ],
      [ "terminal", "namespacettx_1_1terminal.html", [
        [ "AbsolutePosition", "structttx_1_1terminal_1_1AbsolutePosition.html", "structttx_1_1terminal_1_1AbsolutePosition" ],
        [ "Capability", "structttx_1_1terminal_1_1Capability.html", "structttx_1_1terminal_1_1Capability" ],
        [ "Terminfo", "structttx_1_1terminal_1_1Terminfo.html", "structttx_1_1terminal_1_1Terminfo" ],
        [ "Cell", "structttx_1_1terminal_1_1Cell.html", "structttx_1_1terminal_1_1Cell" ],
        [ "Color", "structttx_1_1terminal_1_1Color.html", "structttx_1_1terminal_1_1Color" ],
        [ "Cursor", "structttx_1_1terminal_1_1Cursor.html", "structttx_1_1terminal_1_1Cursor" ],
        [ "PrimaryDeviceAttributes", "structttx_1_1terminal_1_1PrimaryDeviceAttributes.html", "structttx_1_1terminal_1_1PrimaryDeviceAttributes" ],
        [ "OperatingStatusReport", "structttx_1_1terminal_1_1OperatingStatusReport.html", "structttx_1_1terminal_1_1OperatingStatusReport" ],
        [ "CursorPositionReport", "structttx_1_1terminal_1_1CursorPositionReport.html", "structttx_1_1terminal_1_1CursorPositionReport" ],
        [ "KittyKeyReport", "structttx_1_1terminal_1_1KittyKeyReport.html", "structttx_1_1terminal_1_1KittyKeyReport" ],
        [ "DarkLightModeDetectionReport", "structttx_1_1terminal_1_1DarkLightModeDetectionReport.html", "structttx_1_1terminal_1_1DarkLightModeDetectionReport" ],
        [ "StatusStringResponse", "structttx_1_1terminal_1_1StatusStringResponse.html", "structttx_1_1terminal_1_1StatusStringResponse" ],
        [ "ModeQueryReply", "structttx_1_1terminal_1_1ModeQueryReply.html", "structttx_1_1terminal_1_1ModeQueryReply" ],
        [ "BeginPrompt", "structttx_1_1terminal_1_1BeginPrompt.html", "structttx_1_1terminal_1_1BeginPrompt" ],
        [ "EndPrompt", "structttx_1_1terminal_1_1EndPrompt.html", "structttx_1_1terminal_1_1EndPrompt" ],
        [ "EndInput", "structttx_1_1terminal_1_1EndInput.html", "structttx_1_1terminal_1_1EndInput" ],
        [ "EndCommand", "structttx_1_1terminal_1_1EndCommand.html", "structttx_1_1terminal_1_1EndCommand" ],
        [ "OSC133", "structttx_1_1terminal_1_1OSC133.html", "structttx_1_1terminal_1_1OSC133" ],
        [ "OSC2", "structttx_1_1terminal_1_1OSC2.html", "structttx_1_1terminal_1_1OSC2" ],
        [ "OSC21", "structttx_1_1terminal_1_1OSC21.html", "structttx_1_1terminal_1_1OSC21" ],
        [ "OSC52", "structttx_1_1terminal_1_1OSC52.html", "structttx_1_1terminal_1_1OSC52" ],
        [ "OSC66", "structttx_1_1terminal_1_1OSC66.html", "structttx_1_1terminal_1_1OSC66" ],
        [ "OSC7", "structttx_1_1terminal_1_1OSC7.html", "structttx_1_1terminal_1_1OSC7" ],
        [ "OSC8", "structttx_1_1terminal_1_1OSC8.html", "structttx_1_1terminal_1_1OSC8" ],
        [ "OSC8671", "structttx_1_1terminal_1_1OSC8671.html", "structttx_1_1terminal_1_1OSC8671" ],
        [ "TextAreaPixelSizeReport", "structttx_1_1terminal_1_1TextAreaPixelSizeReport.html", "structttx_1_1terminal_1_1TextAreaPixelSizeReport" ],
        [ "CellPixelSizeReport", "structttx_1_1terminal_1_1CellPixelSizeReport.html", "structttx_1_1terminal_1_1CellPixelSizeReport" ],
        [ "TextAreaSizeReport", "structttx_1_1terminal_1_1TextAreaSizeReport.html", "structttx_1_1terminal_1_1TextAreaSizeReport" ],
        [ "InBandSizeReport", "structttx_1_1terminal_1_1InBandSizeReport.html", "structttx_1_1terminal_1_1InBandSizeReport" ],
        [ "TerminfoString", "structttx_1_1terminal_1_1TerminfoString.html", "structttx_1_1terminal_1_1TerminfoString" ],
        [ "GraphicsRendition", "structttx_1_1terminal_1_1GraphicsRendition.html", "structttx_1_1terminal_1_1GraphicsRendition" ],
        [ "Hyperlink", "structttx_1_1terminal_1_1Hyperlink.html", "structttx_1_1terminal_1_1Hyperlink" ],
        [ "IdMap", "classttx_1_1terminal_1_1IdMap.html", "classttx_1_1terminal_1_1IdMap" ],
        [ "MultiCellInfo", "structttx_1_1terminal_1_1MultiCellInfo.html", "structttx_1_1terminal_1_1MultiCellInfo" ],
        [ "Palette", "classttx_1_1terminal_1_1Palette.html", "classttx_1_1terminal_1_1Palette" ],
        [ "ReflowResult", "classttx_1_1terminal_1_1ReflowResult.html", "classttx_1_1terminal_1_1ReflowResult" ],
        [ "Row", "structttx_1_1terminal_1_1Row.html", "structttx_1_1terminal_1_1Row" ],
        [ "RowGroup", "classttx_1_1terminal_1_1RowGroup.html", "classttx_1_1terminal_1_1RowGroup" ],
        [ "SavedCursor", "structttx_1_1terminal_1_1SavedCursor.html", "structttx_1_1terminal_1_1SavedCursor" ],
        [ "Screen", "classttx_1_1terminal_1_1Screen.html", "classttx_1_1terminal_1_1Screen" ],
        [ "ScrollBack", "classttx_1_1terminal_1_1ScrollBack.html", "classttx_1_1terminal_1_1ScrollBack" ],
        [ "ScrollRegion", "structttx_1_1terminal_1_1ScrollRegion.html", "structttx_1_1terminal_1_1ScrollRegion" ],
        [ "Selection", "structttx_1_1terminal_1_1Selection.html", "structttx_1_1terminal_1_1Selection" ],
        [ "Command", "structttx_1_1terminal_1_1Command.html", "structttx_1_1terminal_1_1Command" ],
        [ "Commands", "classttx_1_1terminal_1_1Commands.html", "classttx_1_1terminal_1_1Commands" ],
        [ "Key", "structttx_1_1terminal_1_1Key.html", "structttx_1_1terminal_1_1Key" ]
      ] ],
      [ "Clipboard", "classttx_1_1Clipboard.html", "classttx_1_1Clipboard" ],
      [ "PrintableCharacter", "structttx_1_1PrintableCharacter.html", "structttx_1_1PrintableCharacter" ],
      [ "DCS", "structttx_1_1DCS.html", "structttx_1_1DCS" ],
      [ "OSC", "structttx_1_1OSC.html", "structttx_1_1OSC" ],
      [ "APC", "structttx_1_1APC.html", "structttx_1_1APC" ],
      [ "CSI", "structttx_1_1CSI.html", "structttx_1_1CSI" ],
      [ "Escape", "structttx_1_1Escape.html", "structttx_1_1Escape" ],
      [ "ControlCharacter", "structttx_1_1ControlCharacter.html", "structttx_1_1ControlCharacter" ],
      [ "EscapeSequenceParser", "classttx_1_1EscapeSequenceParser.html", "classttx_1_1EscapeSequenceParser" ],
      [ "FeatureResult", "structttx_1_1FeatureResult.html", "structttx_1_1FeatureResult" ],
      [ "FocusEvent", "classttx_1_1FocusEvent.html", "classttx_1_1FocusEvent" ],
      [ "KeyEvent", "classttx_1_1KeyEvent.html", "classttx_1_1KeyEvent" ],
      [ "LayoutEntry", "structttx_1_1LayoutEntry.html", "structttx_1_1LayoutEntry" ],
      [ "LayoutNode", "structttx_1_1LayoutNode.html", "structttx_1_1LayoutNode" ],
      [ "LayoutPane", "structttx_1_1LayoutPane.html", "structttx_1_1LayoutPane" ],
      [ "LayoutGroup", "classttx_1_1LayoutGroup.html", "classttx_1_1LayoutGroup" ],
      [ "MouseCoordinate", "classttx_1_1MouseCoordinate.html", "classttx_1_1MouseCoordinate" ],
      [ "MousePosition", "classttx_1_1MousePosition.html", "classttx_1_1MousePosition" ],
      [ "MouseClickTracker", "classttx_1_1MouseClickTracker.html", "classttx_1_1MouseClickTracker" ],
      [ "MouseEvent", "classttx_1_1MouseEvent.html", "classttx_1_1MouseEvent" ],
      [ "MouseScrollProtocol", "structttx_1_1MouseScrollProtocol.html", "structttx_1_1MouseScrollProtocol" ],
      [ "PaneHooks", "structttx_1_1PaneHooks.html", "structttx_1_1PaneHooks" ],
      [ "CreatePaneArgs", "structttx_1_1CreatePaneArgs.html", "structttx_1_1CreatePaneArgs" ],
      [ "Pane", "classttx_1_1Pane.html", "classttx_1_1Pane" ],
      [ "Param", "classttx_1_1Param.html", "classttx_1_1Param" ],
      [ "Subparams", "classttx_1_1Subparams.html", "classttx_1_1Subparams" ],
      [ "Params", "classttx_1_1Params.html", "classttx_1_1Params" ],
      [ "PasteEvent", "classttx_1_1PasteEvent.html", "classttx_1_1PasteEvent" ],
      [ "PopupLayout", "structttx_1_1PopupLayout.html", "structttx_1_1PopupLayout" ],
      [ "Popup", "structttx_1_1Popup.html", "structttx_1_1Popup" ],
      [ "RenderedCursor", "structttx_1_1RenderedCursor.html", "structttx_1_1RenderedCursor" ],
      [ "Renderer", "classttx_1_1Renderer.html", "classttx_1_1Renderer" ],
      [ "Size", "structttx_1_1Size.html", "structttx_1_1Size" ],
      [ "SetClipboard", "structttx_1_1SetClipboard.html", "structttx_1_1SetClipboard" ],
      [ "WritePtyString", "structttx_1_1WritePtyString.html", "structttx_1_1WritePtyString" ],
      [ "ModeHandler", "structttx_1_1ModeHandler.html", "structttx_1_1ModeHandler" ],
      [ "Terminal", "classttx_1_1Terminal.html", "classttx_1_1Terminal" ],
      [ "TerminalInputParser", "classttx_1_1TerminalInputParser.html", "classttx_1_1TerminalInputParser" ],
      [ "Utf8StreamDecoder", "classttx_1_1Utf8StreamDecoder.html", "classttx_1_1Utf8StreamDecoder" ],
      [ "ModeQuery", "structttx_1_1ModeQuery.html", "structttx_1_1ModeQuery" ],
      [ "TerminfoQuery", "structttx_1_1TerminfoQuery.html", "structttx_1_1TerminfoQuery" ],
      [ "FeatureDetector", "classttx_1_1FeatureDetector.html", "classttx_1_1FeatureDetector" ],
      [ "CodePointMapping", "structttx_1_1CodePointMapping.html", "structttx_1_1CodePointMapping" ],
      [ "FindPaneInLayoutGroup", "structttx_1_1FindPaneInLayoutGroup.html", null ],
      [ "GetRelativeSize", "structttx_1_1GetRelativeSize.html", null ],
      [ "ToJsonV1", "structttx_1_1ToJsonV1.html", null ],
      [ "FromJsonV1", "structttx_1_1FromJsonV1.html", null ],
      [ "MakePane", "structttx_1_1MakePane.html", "structttx_1_1MakePane" ],
      [ "ButtonMapping", "structttx_1_1ButtonMapping.html", "structttx_1_1ButtonMapping" ],
      [ "ResolveSize", "structttx_1_1ResolveSize.html", null ],
      [ "Change", "structttx_1_1Change.html", "structttx_1_1Change" ]
    ] ]
];