name: Darwin CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  darwin_build_and_test:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: macos-latest
    strategy:
      matrix:
        preset: [ci-macos]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Store ccache cache in the GitHub actions cache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.preset }}
      - name: Configure build
        run: |
          nix develop --command cmake --preset ${{ matrix.preset }} -DCMAKE_COMPILE_WARNING_AS_ERROR=On
      - name: Run build
        run: |
          nix develop --command cmake --build --preset ${{ matrix.preset }}
      - name: Run tests
        run: |
          nix develop --command ctest --preset ${{ matrix.preset }}
